name: Deploy

on:
  push:
    branches:
      - main  # Triggers the workflow on push events to the 'main' branch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest  # The latest Ubuntu environment

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3  # Checks out the repository code

      - name: Setup Node
        uses: actions/setup-node@v3  # Sets up the Node.js environment

      - name: Install dependencies
        uses: bahmutov/npm-install@v1  # Installs npm dependencies

      - name: Build project
        run: npm run build  # Runs the build script defined in package.json

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3  # Uploads the build files as an artifact
        with:
          name: production-files
          path: ./dist  # Path to the build files

  deploy:
    name: Deploy
    needs: build  # Specifies that 'deploy' job depends on 'build' job
    runs-on: ubuntu-latest  # The latest Ubuntu environment
    if: github.ref == 'refs/heads/main'  # Ensures this job runs only on pushes to 'main' branch

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3  # Downloads the artifact produced in the build job
        with:
          name: production-files
          path: ./dist  # Path where the artifact will be downloaded

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # Deploys the contents to GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Uses GitHub token for authentication
          publish_dir: ./dist  # Directory to publish to GitHub Pages
